# Generated by Django 2.1.5 on 2019-02-13 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20190212_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
