# Generated by Django 2.1.5 on 2019-02-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='time',
        ),
    ]
